name: Synchronize Insight.com Labels
on:
  push:
    branches:
      - main
      - test-lokalise


jobs:
  Synchronize-labels:
    name: Synchronize
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout ecom-services
        uses: actions/checkout@v2
        with:
          repository: Insight-IT-Web/ecom-services
          path: ecom-services
          ref: lokalise
          clean: true
          token: ${{ secrets.TF_GITHUB_TOKEN }}
      - name: Checkout iw-prototype
        uses: actions/checkout@v2
        with:
          repository: Insight-IT-Web/iw-prototype
          path: iw-prototype
          ref: lokalise
          clean: true
          token: ${{ secrets.TF_GITHUB_TOKEN }}
      - name: Synchronize ecom-services labels
        working-directory: ecom-services
        run: |
          rm -Rf ecom-services/web/insightweb/labels
          ls -ltr
          pwd
          cp -R ../lokalise/insightweb/labels/ web/insightweb/
          git remote set-url origin https://${{ secrets.TF_TF_GITHUB_TOKEN }}@github.com/Insight-IT-Web/ecom-services.git
          git status
          git add .
          git status
          git commit -m "PRT-1234 synchronizing insight.com labels"
          git push
        shell: bash
     # - name: Synchronize iw-prototype labels
      #  working-directory: iw-prototype
       # run: |
        #  rm -Rf packages/app-header/labels
         # cp -R ../lokalise/app-header/labels/ packages/app-header/labels
          #git remote set-url origin https://${{ secrets.TF_TF_GITHUB_TOKEN }}@github.com/Insight-IT-Web/iw-prototype.git
         # git status
         # git add .
         # git status
         # git commit -m "PRT-1234 synchronizing insight.com labels"
         # git push
        #shell: bash
